set_project("my_proj_name")
option("meso_proj",{default="none", showmenu=true})
add_rules("plugin.vsxmake.autoupdate")

--add_rules("mode.releasedbg","mode.release","mode.debug")
add_rules("mode.debug")
-- set_targetdir("../../bin/_tests_reservoir")
includes("src/reservoir/xmake.lua")
target("_tests_reservoir")
    set_kind("binary")
    add_headerfiles("proj/_tests_reservoir/*.h")
    add_files("proj/_tests_reservoir/*.cpp","proj/_tests_reservoir/*.cu")
    add_cugencodes("native")
    add_cugencodes("compute_61")
    add_deps("reservoir")