add_requires("eigen >=3.4.0")
add_requires("fmt >=8.1.1")
add_requires("nlohmann_json >=3.10.5")
add_requires("boost >=1.78.0")
add_requires("cuda", {system=true, configs={utils={"cublas","cusparse","cusolver"}}})
add_rules("mode.debug","mode.release")
--set_languages("cxx20")
--includes("./../../src/common/xmake.lua")
target("fluid_euler_two_phase_clebsch")
    add_rules("plugin.vsxmake.autoupdate")
    set_kind("binary")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu","*.cxx")
    add_cugencodes("native")
    add_cugencodes("compute_61")
    add_packages("cuda",{public=true})
    add_packages("eigen",{public=true})
    add_packages("fmt",{public=true})
    add_packages("nlohmann_json",{public=true})
    add_packages("boost",{public=true})
    add_cuflags("--extended-lambda")
    --add_deps("common")
