includes("./../../src/common/xmake.lua")
--add_rules("plugin.vsxmake.autoupdate")
target("geometry")
    set_kind("static")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu","*.cxx")
    add_cugencodes("native","compute_61")
    add_cuflags("-extended-lambda --std c++17")
    add_includedirs(".",{public=true})
    add_deps("common")
    