add_rules("mode.debug","mode.release")
includes("./../../src/common/xmake.lua")
includes("./../../src/solver/xmake.lua")
includes("./../../src/optimization/xmake.lua")
includes("./../../src/reservoir/xmake.lua")
includes("./../../src/geometry/xmake.lua")
includes("./../../src/mesh_algorithm/xmake.lua")
add_requires("vtk >=9.1.0")
target("thin_shell")
    add_rules("plugin.vsxmake.autoupdate")
    set_kind("binary")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu","*.cxx")
    add_cugencodes("native")
    add_cugencodes("compute_61")
    add_cuflags("--extended-lambda")
    add_cuflags("-Xcompiler /openmp")
    add_packages("vtk",{public=true})
    add_deps("common")
    add_deps("solver")
    add_deps("optimization")
    add_deps("reservoir")
    add_deps("mesh_algorithm")
    add_deps("geometry")
