includes("./../../src/reservoir/xmake.lua")
includes("./../../src/solver/xmake.lua")
target("dec_system")
    set_kind("static")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu","*.cxx")
    add_cugencodes("native")
    add_cugencodes("compute_61")
    add_cuflags("--extended-lambda --std c++17 -Xcompiler /openmp")
    add_includedirs(".",{public=true})
    add_deps("solver","reservoir")