add_rules("mode.debug","mode.release")
set_languages("cxx17")
includes("./../../src/grid_algorithm/xmake.lua")
includes("./../../src/dec_system/xmake.lua")
target("fluid_hybrid")
    add_rules("plugin.vsxmake.autoupdate")
    set_kind("binary")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu","*.cxx")
    add_cugencodes("native","compute_61")
    add_cuflags("-extended-lambda --std c++17","-Xcompiler /bigobj")
    add_deps("grid_algorithm")
    add_deps("dec_system")
