add_rules("mode.release", "mode.debug")
set_languages("cxx20")
includes("./../../src/geometry/xmake.lua")
includes("./../../src/reservoir/xmake.lua")
includes("./../../src/solver/xmake.lua")

target("_tests_kernel")
    add_rules("plugin.vsxmake.autoupdate")
    set_kind("binary")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu")
    add_cugencodes("native","compute_61")
    add_cuflags("-extended-lambda --std c++17")
    add_deps("geometry","reservoir","solver")
