includes("./../../src/reservoir/xmake.lua")
includes("./../../src/geometry/xmake.lua")
includes("./../../src/solver/xmake.lua")
target("particle_algorithm")
    set_kind("static")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu","*.cxx")
    add_cugencodes("native")
    add_cugencodes("compute_61")
    add_cuflags("-extended-lambda")
    add_cuflags("-Xcompiler /openmp")
    add_includedirs(".",{public=true})
    add_deps("reservoir")
    add_deps("geometry")
    add_deps("solver")