includes("./../../src/common/xmake.lua")
-- add_rules("plugin.vsxmake.autoupdate")
add_requires("nanoflann")
add_requires("vtk >=9.1.0")
add_requires("libigl >= 2.4.0")
target("reservoir")
    set_kind("static")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu","*.cxx")
    add_cugencodes("native","compute_61")
    add_cuflags("-extended-lambda --std c++17")
    add_includedirs(".",{public=true})
    add_packages("vtk",{public=true})
    add_packages("nanoflann",{public=true})
    add_packages("libigl",{public=true})
    add_deps("common")
    