includes("./../../src/common/xmake.lua")
target("reservoir")
    set_kind("static")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu")
    add_includedirs(".",{public=true})
    add_deps("common")