includes("./../../src/common/xmake.lua")
-- add_rules("plugin.vsxmake.autoupdate")
target("reservoir")
    set_kind("static")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu")
    add_cugencodes("native")
    add_cugencodes("compute_61")
    add_includedirs(".",{public=true})
    add_deps("common")