includes("./../../src/common/xmake.lua")
target("solver")
    set_kind("static")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu","*.cxx")
    add_cugencodes("native","compute_61")
    add_cuflags("-extended-lambda --std c++17")
    add_packages("mma",{public=true})
    add_includedirs(".",{public=true})
    add_packages("eigen",{public=false})
    add_deps("common")