includes("./../../src/common/xmake.lua")
target("solver")
    set_kind("static")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu","*.cxx")
    add_cugencodes("native")
    add_cugencodes("compute_61")
    add_packages("mma",{public=true})
    add_cuflags("-extended-lambda --std c++17")
    add_cuflags("-Xcompiler /openmp")
    add_includedirs(".",{public=true})
    add_deps("common")