includes("./../../src/common/xmake.lua")
add_requires("mma >=2018.08.01")
target("solver")
    set_kind("static")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu","*.cxx")
    add_cugencodes("native")
    add_cugencodes("compute_61")
    add_packages("mma",{public=true})
    add_cuflags("-extended-lambda")
    add_includedirs(".",{public=true})
    add_deps("common")