add_rules("mode.debug","mode.release")
set_languages("cxx17")
includes("./../../src/particle_algorithm/xmake.lua")
includes("./../../src/grid_algorithm/xmake.lua")
includes("./../../src/reservoir/xmake.lua")
target("melp")
    add_rules("plugin.vsxmake.autoupdate")
    set_kind("binary")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu","*.cxx")
    add_cugencodes("native","compute_61")
    add_cuflags("-extended-lambda --std c++17")
    add_deps("particle_algorithm")
    add_deps("grid_algorithm")
    add_deps("reservoir")