add_rules("mode.release","mode.debug")
--set_languages("cxx20")
includes("./../../src/solver/xmake.lua")
target("_tests_solver")
    add_rules("plugin.vsxmake.autoupdate")
    set_kind("binary")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu","*.cxx")
    add_cugencodes("native","compute_61")
    add_cuflags("-extended-lambda --std c++17", "-Xcompiler /openmp")
    add_deps("solver")
