add_rules("mode.debug","mode.release","mode.releasedbg")
add_requires("openmp")
--set_languages("cxx20")
includes("./../../src/dec_system/xmake.lua")
includes("./../../src/grid_physics/xmake.lua")
target("fluid_clebsch")
    add_rules("plugin.vsxmake.autoupdate")
    set_kind("binary")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu","*.cxx")
    add_cugencodes("native","compute_61")
    add_cuflags("-extended-lambda --std c++17")
    add_deps("grid_physics")
    add_deps("dec_system")
