add_requires("eigen >=3.4.0")
add_requires("fmt >=8.1.1")
target("common")
    set_kind("static")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu")
    add_includedirs(".",{public=true})
    add_packages("eigen",{public=true})
    add_packages("fmt",{public=true})