add_requires("eigen >=3.4.0")
add_requires("fmt >=8.1.1")
add_requires("cuda", {system=true, configs={utils={"cublas","cusparse"}}})
target("common")
    set_kind("static")
    add_headerfiles("*.h")
    --add_files("*.cpp","*.cu")
    add_files("*.cpp","*.cu","*.cxx")
    add_includedirs(".",{public=true})
    add_packages("cuda",{public=true})
    add_packages("eigen",{public=true})
    add_packages("fmt",{public=true})