-- set_project("_tests_reservoir")
add_rules("plugin.vsxmake.autoupdate")
--add_rules("mode.releasedbg","mode.release","mode.debug")
add_rules("mode.debug")
-- set_targetdir("../../bin/_tests_reservoir")
includes("./../../src/reservoir/xmake.lua")
target("_tests_reservoir")
    set_kind("binary")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu")
    add_cugencodes("native")
    add_cugencodes("compute_61")
    add_deps("reservoir")
