set_project("_tests_reservoir")
add_rules("plugin.vsxmake.autoupdate")
add_rules("mode.releasedbg","mode.release","mode.debug")
set_targetdir("../../bin/_tests_reservoir")
-- includes("./../../src/common/xmake.lua")
includes("./../../src/reservoir/xmake.lua")
target("_tests_reservoir")
    set_kind("binary")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu")
    add_deps("reservoir")
