set_project("_tests_reservoir")
add_rules("plugin.vsxmake.autoupdate")
--add_rules("mode.releasedbg","mode.release","mode.debug")
add_rules("mode.debug")
local targetdir = "../../bin/_tests_reservoir"
set_targetdir(targetdir)
set_objectdir(targetdir.."/.objs")--it's like "+" in Python
set_dependir(targetdir.."/.deps")
includes("./../../src/reservoir/xmake.lua")
target("_tests_reservoir")
    set_kind("binary")
    add_headerfiles("*.h")
    add_files("*.cpp","*.cu")
    add_cugencodes("native")
    add_cugencodes("compute_61")
    add_deps("reservoir")
